apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger-python-client-sample
  labels:
    app: jaeger-python-client-sample
spec:
  template:
    metadata:
      labels:
        app: jaeger-python-client-sample
    spec:
      containers:
      - image:  snowdeer/openshift-jaegar-python-sample:latest
        name: jaeger-python-client-sample
        ports:
        - containerPort: 8080
          protocol: TCP
      
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-python-client-sample
  labels:
    app: jaeger-python-client-sample
spec:
  ports:
  - name: jaeger-python-client-sample
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jaeger-python-client-sample
  type: LoadBalancer