apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: jaeger-python-sample
  name: jaeger-python-sample
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/snowdeer/openshift-jaeger-python-client-sample.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'ubuntu:latest'
        
    type: Docker    
  successfulBuildsHistoryLimit: 5 
  output:
    to:
      kind: ImageStreamTag
      name: 'jaeger-python-sample:latest'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger-python-sample
  labels:
    app: jaeger-python-sample
spec:
  template:
    metadata:
      labels:
        app: jaeger-python-sample
    spec:
      containers:
      - image:  snowdeer/jaeger-python-sample:latest
        name: jaeger-python-sample
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-python-sample
  labels:
    app: jaeger-python-sample
spec:
  ports:
  - name: jaeger-python-sample
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jaeger-python-sample
  type: LoadBalancer